"""items per page

Revision ID: f199adb7c679
Revises: d51c69ca6f98
Create Date: 2019-01-26 22:50:30.573706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f199adb7c679'
down_revision = 'd51c69ca6f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ticker_per_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ticker_per_page')
    # ### end Alembic commands ###
